services:
  infohub-file-manager:
    container_name: infohub-file-manager
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ARG_UID: ${UID:-1000}
        ARG_GID: ${GID:-1000}
    ports:
      - "8500:8500"
    volumes:
      - "./config.json:/app/config.json"
      - "./infohub.log:/app/infohub.log"
      - "./data:/data"
    restart: unless-stopped
